fr:
  :domain: "webservices.amazon.fr"
  :associate_tag: "charlieschapl-21"
  :secret_key: 'JBJVLPZ5Jjp3BX9gV27G6fiG/mR+8ssR4xyb2r7a'
  
us:
  :domain: "webservices.amazon.com"
  :associate_tag: "charliechap0e-20"
  :secret_key: 'JBJVLPZ5Jjp3BX9gV27G6fiG/mR+8ssR4xyb2r7a'
  
uk:
  :domain: "webservices.amazon.co.uk"
  :associate_tag: "charlchapl-21"
  :secret_key: 'JBJVLPZ5Jjp3BX9gV27G6fiG/mR+8ssR4xyb2r7a'

ca:
  :domain: "webservices.amazon.ca"
  :associate_tag: "charlchapl-20"
  :secret_key: 'JBJVLPZ5Jjp3BX9gV27G6fiG/mR+8ssR4xyb2r7a'
  
#  :us => 'http://ecs.amazonaws.com/onca/xml',
#  :uk => 'http://ecs.amazonaws.co.uk/onca/xml',
#  :ca => 'http://ecs.amazonaws.ca/onca/xml',
#  :de => 'http://ecs.amazonaws.de/onca/xml',
#  :jp => 'http://ecs.amazonaws.jp/onca/xml',
#  :fr => 'http://ecs.amazonaws.fr/onca/xml'